listen:
  host: ${LISTEN_HOST}
  port: ${LISTEN_PO RT}

storage:
  dir: ${STORAGE_DIR}
  cache: ${STORAGE_CACHE}

behavior:
  dependency_isolation: ${BEHAVIOR_DEPENDENCY_ISOLATION}
  kernel_isolation: ${BEHAVIOR_KERNEL_ISOLATION}

ui:
  base_uri: ${UI_BASE_URI}
