listen:
  host: ${LISTEN_HOST}
  port: ${LISTEN_PORT}

storage:
  dir: ${STORAGE_DIR}
  cache: ${STORAGE_CACHE}

behavior:
  dependency_isolation: ${BEHAVIOR_DEPENDENCY_ISOLATION}
  kernel_isolation: ${BEHAVIOR_KERNEL_ISOLATION}

spark:
  spark.driver.userClasspathFirst: ${SPARK_SPARK_DRIVER_USERCLASSPATHFIRST}
  spark.executor.userClasspathFirst: ${SPARK_SPARK_EXECUTOR_USERCLASSPATHFIRST}

ui:
  base_uri: ${UI_BASE_URI}
