base_dockerfile_template: |
  ARG JAVA_VERSION=""

  FROM openjdk:${{JAVA_VERSION}}

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ENV POLYNOTE_HOME "/polynote"
  ENV PATH=${{POLYNOTE_HOME}}:$PATH \
  {env_vars}

  ADD config_template.yml config_loader.py entrypoint.sh ./

  RUN apt-get update && \
      apt-get -y install python3 python3-pip && \
      rm -rf /var/lib/apt/lists/* && \
      pip3 install setuptools pyyaml jep jedi virtualenv matplotlib && \
      mkdir -p ${{POLYNOTE_HOME}} && \
      chmod +x entrypoint.sh

config_files:
  - path: polynote_configs/config-template.yml
    filename: config_template.yml

output_dir: ../../base