# Written by Mutlu Polatcan

name: Polynote Docker Image Publish

on: [push]

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [polynote]
        java_version: [8,11]
        spark_version: [2.4.4, 2.3.4]
        spark_hadoop_version: [2.7]
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-spark-${{matrix.spark_version}}-java${{matrix.java_version}}
          --build-arg SPARK_VERSION=${{matrix.spark_version}}
          --build-arg SPARK_HADOOP_VERSION=${{matrix.spark_hadoop_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-spark-${{matrix.spark_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-spark-${{matrix.spark_version}}-java${{matrix.java_version}}

  build-setup-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [polynote]
        java_version: [8,11]
        polynote_version: [0.2.11]
        spark_version: [2.4.4, 2.3.4]
    needs: build-base-image
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.polynote_version}}-spark-${{matrix.spark_version}}-java${{matrix.java_version}}}}
          --build-arg POLYNOTE_VERSION=${{matrix.polynote_version}}
          --build-arg SPARK_VERSION=${{matrix.spark_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/setup
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.polynote_version}}-spark-${{matrix.spark_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.polynote_version}}-spark-${{matrix.spark_version}}-java${{matrix.java_version}}
